language: ruby
rvm:
  - 2.6
env:
  - CODECOV_TOKEN=aab48030-1d1c-4eba-b865-804baac9100f
before_install:
  - gem update --system
  - gem install bundler
script:
  - bundle exec rake spec
after_success:
  - codecov
